export enum ErrorTypes {
	BAD_REQUEST = 'BAD_REQUEST',
	UNAUTHORIZED = 'UNAUTHORIZED',
	NOT_FOUND = 'NOT_FOUND',
	NOT_ALLOWED = 'NOT_ALLOWED',
	UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
}

export const HTTP_CODE_BY_ERROR: { [key: string]: number } = {
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	NOT_FOUND: 404,
	NOT_ALLOWED: 405,
	UNPROCESSABLE_ENTITY: 422,
};
